### ISSUE TITLE
Don't store job data in /tmp

### ISSUE THREAD

**Issue by davidread** [ckan/datapusher#129]
The default place to store the jobs is:

    SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/job_store.db'

and tmp is wiped on reboot (or even [daily](http://askubuntu.com/questions/20783/how-is-the-tmp-directory-cleaned-up/759048#759048))

This is no good, because it results in problems like this:
https://github.com/ckan/ckan/issues/3156

We should store it somewhere better by default.

**Comment by torfsen** [comment]
CKAN's storage directory would be a good place. We've recently discussed moving the generated JS translations there, too (ckan/ckan#3461).

**Comment by davidread** [comment]
Nice, although I was thinking postgres. It's got to be written to by multiple threads.

**Comment by torfsen** [comment]
You're right, since it's already a database putting it into Postgres would be a better indeed.

**Comment by izhangzhihao** [comment]
Any progress?

**Comment by davidread** [comment]
@izhangzhihao We've discussed what would be a good way forward, but no-one's offered to do it, I'm afraid. If it is a concern for you, please do offer to do (or fund) a pull request, in the usual open source way.

**Comment by izhangzhihao** [comment]
Good, I will try to find some time to do it. Now I'm just put the `job_store.db` to a volume.
