### ISSUE TITLE
SSL_VERIFY doesn't work

### ISSUE THREAD

**Issue by davidread** [ckan/datapusher#149]
The [docs](http://docs.ckan.org/projects/datapusher/en/latest/using.html#configuring-ssl-verification) say you can set ```SSL_VERIFY = False``` in the datapusher settings to avoid checking SSL certs. However my tests show this doesn't work - the settings are not getting through to jobs.py.

**Comment by davidread** [comment]
@Zharktas you've been using SSL_VERIFY recently - did you encounter any problems? 

datapusher/main.py imports jobs straight away, which sets the SSL_VERIFY value from web.app.config.get('SSL_VERIFY'), however that is the Flask settings which are not set-up yet. Only afterwards does main.py put the command-line argument (e.g. settings.py) into JOB_CONFIG and then start the Flask app (web.py), which (trys to) add those options to the web.app.config (in _configure_app).

**Comment by Zharktas** [comment]
@davidread Yes, we have been using it in our dev environments with CKAN 2.7. however False must be given as string ie. SSL_VERIFY = 'False'

Example in our repo https://github.com/6aika/sixodp/blob/master/ansible/roles/datapusher/templates/datapusher_settings.py.j2#L29 which I just tested locally :p

**Comment by metaodi** [comment]
`False` and `0` are now accepted values as well (see #150)
