### ISSUE TITLE
Is it possible to install DATAPUSHER (production installation) in a CKAN last version with Python 3.x? 

### ISSUE THREAD

**Issue by scoutinhoGit** [ckan/datapusher#186]
Hi,

I have installed the last version of CKAN (source install) on UBUNTU 18 (with Python 3.x), and i would like to know if it´s possible to install DATAPUSHER production version in this environment.

I have read documentation on https://docs.ckan.org/projects/datapusher/en/latest/,  but i´m afraid these instructions are to install DATAPUSHER with python 2.x.

Is it possible to install DATAPUSHER (package or production version) with CKAN last version with Python 3.x? Which is the best or more complete guide to proceed with this installation?

Best regards,

Sergio

**Comment by amercader** [comment]
Not yet @scoutinhoGit , I've created https://github.com/ckan/datapusher/issues/187 to track progress https://github.com/ckan/datapusher/issues/187
