### ISSUE TITLE
Documentation needs to be rebuilt to reflect latest simplified deployment instructions

### ISSUE THREAD

**Issue by jqnatividad** [ckan/datapusher#203]
The latest datapusher documentation still has the old guidance

https://docs.ckan.org/projects/datapusher/en/latest/deployment.html

and does not reflect the latest simplified deployment

https://github.com/ckan/datapusher/blob/master/doc/deployment.rst

It might also be nice if a supervisor configuration is included.

**Comment by amercader** [comment]
Updated now, for some reason the Read the Docs webhook wasn't configured
