### ISSUE TITLE
Datapusher inferring column type incorrectly.

### ISSUE THREAD

**Issue by scuerda** [ckan/datapusher#48]
Received the following errors while pushing data via the API. The dataset in question has a column whose initial values are numeric (first row entry is 1) but later values are strings ("K"). It appears that the inference routine is inferring type from initial rows and is therefore never seeing the first instance of a "K" value which doesn't show up until ~1000 rows in.

Is it possible to either a) have the  scheme generated off of unique col values vs. 1st/initial row values or b) allow for a user defined schema to be passed in when adding a resource?

```
[Thu Oct 16 15:50:30 2014] [error] Job "push_to_datastore (trigger: RunTriggerNow, run = True,    next run at: None)" raised an exception
[Thu Oct 16 15:50:30 2014] [error] Traceback (most recent call last):
[Thu Oct 16 15:50:30 2014] [error]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
[Thu Oct 16 15:50:30 2014] [error]     retval = job.func(*job.args, **job.kwargs)
[Thu Oct 16 15:50:30 2014] [error]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 322, in push_to_datastore
[Thu Oct 16 15:50:30 2014] [error]     records, api_key, ckan_url)
[Thu Oct 16 15:50:30 2014] [error]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 150, in send_resource_to_datastore
[Thu Oct 16 15:50:30 2014] [error]     check_response(r, url, 'CKAN DataStore')
[Thu Oct 16 15:50:30 2014] [error]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 84, in check_response
[Thu Oct 16 15:50:30 2014] [error]     resp=pprint.pformat(json_response)))
[Thu Oct 16 15:50:30 2014] [error] JobError: CKAN DataStore bad response. Status code: 409 Conflict. At: http://68.169.49.221:8088/api/3/action/datastore_create. Response: {u'error': {u'__type':  u'Validation Error',
[Thu Oct 16 15:50:30 2014] [error]             u'data': u'(DataError) invalid input syntax for type numeric: "K"\\nLINE 2:             VALUES (\\'Andover\\', 901301080, 2008, \\'K\\', \\'Percen...\\n                                                        ^\\n',
[Thu Oct 16 15:50:30 2014] [error]             u'info': {u'orig': [u'invalid input syntax for type numeric: "K"\\nLINE 2:             VALUES (\\'Andover\\', 901301080, 2008, \\'K\\', \\'Percen...\\n                                                        ^\\n']}},
```

**Comment by slnovak** [comment]
:+1: for this as well. I'm attempting to upload a 11MB CSV file and I get a similar error after ~16k lines.

**Comment by Moqri** [comment]
Same issue here

**Comment by davidread** [comment]
If you want to add a config option to increase the sample size, then please go ahead. Obviously a high size affects performance and so will not suit everyone.

Otherwise we've talked about [making the schema editable for a resource](https://github.com/ckan/ideas-and-roadmap/issues/150), so that you can manually set the column types and avoid the issue that way.

**Comment by scuerda** [comment]
I'm going to close this issue at this point in time and open up a separate issue (and hopefully a PR shortly following) for some better documentation on the datapusher and the assignment of column types. There are a bunch of ways to "trick" the datapusher (sorting uploaded data to get values that will be "correctly" parsed to the top, adding rules to the messytables config, etc.) and it's probably more useful for new users to get a better picture of how and why the datapusher does what it does. 

That said, I manually editable schemas (maybe even piggybacking off of datapackage.json schema declarations) would be a fantastic step imo. Thanks.

**Comment by wardi** [comment]
@scuerda ckan master supports user-editable data dictionaries that datapusher is already aware of. That would be a great place for users to be able to select a data type to override the one datapusher chooses when re-uploading a dataset.
