### ISSUE TITLE
Connection timed out when updloading using datapusher...

### ISSUE THREAD

**Issue by ainslied** [ckan/datapusher#62]
Hi, I get an error when trying to uploading a file.. :
>[error] /usr/lib/ckan/datapusher/lib/python2.7/site-packages/sqlalchemy/engine/default.py:585: SAWarning: Unicode type received non-unicodebind param value.
[error]   processors[key](compiled_params[key])
[error] Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
[error] Traceback (most recent call last):
[error]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
[error]     retval = job.func(*job.args, **job.kwargs)
[error]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 222, in push_to_datastore
[error]     resource = get_resource(resource_id, ckan_url, api_key)
[error]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 178, in get_resource
[error]     'Authorization': api_key}
[error]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/api.py", line 99, in post
[error]     return request('post', url, data=data, json=json, **kwargs)
[error]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/api.py", line 49, in request
[error]     response = session.request(method=method, url=url, **kwargs)
[error]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
[error]     resp = self.send(prep, **send_kwargs)
[error]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
[error]     r = adapter.send(request, **kwargs)
[error]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
[error]     raise ConnectionError(err, request=request)
[error] ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))

Here is an extract of my configuration :
in /etc/apache2/sites-available/datapusher
><VirtualHost 0.0.0.0:8800>
WSGIScriptAlias / /etc/ckan/datapusher.wsgi

in /etc/apache2/ports.conf
>NameVirtualHost *:8800
Listen 8800

in /etc/apache2/sites-available/ckan
>WSGIScriptAlias /ckan /etc/ckan/default/apache.wsgi

in /etc/ckan/datapusher_settings.py
>SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/job_store.db'
HOST = '0.0.0.0'
PORT = 8800

This file is not well documented.. Is there something else to configure (like SQLALCHEMY_DATABASE_URI in order to use postgres for example?)
I tried also to create an other database for dp : SQLALCHEMY_DATABASE_URI = 'postgresql://user:pass@localhost/ckan_dp_default', doesnt work better.

in /etc/ckan/default/development.ini / production.ini
>ckan.site_url = http://www.domain.com/ckan
ckan.plugins = stats text_preview recline_preview datastore pdf_preview resource_proxy datapusher spatial_metadata spatial_query geojson_preview
ckan.datapusher.url = http://0.0.0.0:8800/

datastore is installed too..

I really don't understand why I get this error, and I read nobody else with this error..
Do you have any idea..? If not, how could I debug this?

Thank you,
Regards,
AD

**Comment by joetsoi** [comment]
@ainslied is this still an issue? if it is could you send it to the ckan-dev mailing list where it'll probably be seen by more people
