### ISSUE TITLE
Size of backlog is opaque

### ISSUE THREAD

**Issue by rossjones** [ckan/datapusher#68]
It doesn't seem to be possible to see what the current datapusher backlog is because there doesn't seem to be a way to inspect its internal queue.

**Comment by joetsoi** [comment]
I can't remember distinctly, but there is a /jobs which might be helpful? You'll need to login as an admin to the datapusher

**Comment by amercader** [comment]
As per http://ckan-service-provider.readthedocs.org/en/latest/

**Comment by rossjones** [comment]
That sounds perfect, would be awesome for this to be exposed via the admin tab (perhaps).  Will add it to the ideas repo for now and close this one.
