### ISSUE TITLE
datapusher issue to upload a CSV into datastore

### ISSUE THREAD

**Issue by morettidmn** [ckan/datapusher#76]
I have ckan 2.3, I tried to install datapusher (last stable) and it seems to work, but when I load a CSV file and click to Upload to datastore, I get a "Process completed but unable to post to result_url" error.

in /var/log/apache2/datapusher.error.log:

_[Wed Jun 17 09:03:15 2015] [error] Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
[Wed Jun 17 09:03:15 2015] [error] Traceback (most recent call last):
[Wed Jun 17 09:03:15 2015] [error]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
[Wed Jun 17 09:03:15 2015] [error]     retval = job.func(_job.args, *_job.kwargs)
[Wed Jun 17 09:03:15 2015] [error]   File "/root/ckan/lib/datapusher/src/datapusher/datapusher/jobs.py", line 226, in push_to_datastore
[Wed Jun 17 09:03:15 2015] [error]     resource = get_resource(resource_id, ckan_url, api_key)
[Wed Jun 17 09:03:15 2015] [error]   File "/root/ckan/lib/datapusher/src/datapusher/datapusher/jobs.py", line 180, in get_resource
[Wed Jun 17 09:03:15 2015] [error]     check_response(r, url, 'CKAN')
[Wed Jun 17 09:03:15 2015] [error]   File "/root/ckan/lib/datapusher/src/datapusher/datapusher/jobs.py", line 91, in check_response
[Wed Jun 17 09:03:15 2015] [error]     resp=response.text[:200]))
[Wed Jun 17 09:03:15 2015] [error] JobError: CKAN bad response. Status code: 404 Not Found. At: http://127.0.0.1/api/3/action/resource_show. Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
[Wed Jun 17 09:03:15 2015] [error] <html><head>
[Wed Jun 17 09:03:15 2015] [error] <title>404 Not Found</title>
[Wed Jun 17 09:03:15 2015] [error] </head><body>
[Wed Jun 17 09:03:15 2015] [error] <h1>Not Found</h1>
[Wed Jun 17 09:03:15 2015] [error] <p>The requested URL /api/3/action/resource_show was not found on this ser_

Any ideas?

**Comment by morettidmn** [comment]
in the same log:

[Fri Jun 19 08:10:32 2015] [error] /usr/lib/ckan/datapusher/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '4b0a243c-2fde-4047-87d7-6...'. (this warning may be suppressed after 10 occurrences)

please help us!

**Comment by davidread** [comment]
It looks like datapusher failed doing the callback to ckan. This is probably because your ckan.site_url is not configured correctly.

Since this occurred, better logging for this has been added.
