### ISSUE TITLE
Check whether file has changed

### ISSUE THREAD

**Issue by domoritz** [ckan/datapusher#9]
Check last modified header or hash.

**Comment by NicolaiMogensen** [comment]
Could this be implemented for resources where the file is not a local file, but an URL?

**Comment by amercader** [comment]
This would be very costly as we would need to redownload all files regularly and compute a hash from them. For uploaded files we can do it as we need to read the file being uploaded anyway.

**Comment by NicolaiMogensen** [comment]
What about checking the `content-length` header. I know this is not a perfect indicator, but could be used to check if the file size has changed.
