### ISSUE TITLE
Incorrect deployment docs

### ISSUE THREAD

**Issue by drnextgis** [ckan/datapusher#97]
From [here](http://docs.ckan.org/projects/datapusher/en/latest/deployment.html):

```
#create a virtualenv for datapusher
sudo virtualenv /usr/lib/ckan/datapusher
```

But in the rest part of the document - virtual environment is not used.

**Comment by amercader** [comment]
@drnextgis It is used. When you run commands like:

```
sudo /usr/lib/ckan/datapusher/bin/pip install -r requirements.txt
sudo /usr/lib/ckan/datapusher/bin/python setup.py develop
```

you are running the `pip` version installed in the virtualenv, and installing the requirements in the virtualenv. Also the [wsgi file](https://github.com/ckan/datapusher/blob/master/deployment/datapusher.wsgi#L5) points to the virtualenv as well.

Does this make sense?
